### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by fudoakira** [fudoakira/protospace-37207#1]
# URL
https://protospace-37207.herokuapp.com/

**Comment by snkw-works** [comment]
@fudoakira さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **プロトタイプ編集ページにて、バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないよう修正しましょう**
空欄がある状態で保存ボタンをクリックすると、入力済みの項目が消えてしまいます。

https://user-images.githubusercontent.com/54050089/152710091-384f5efa-93d0-4216-a0c3-90e59611ae4d.mov

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
・ユーザー名が正しく表示されていない状態です。
・そのユーザーが投稿したプロトタイプが表示されない状態です。
<img width="1196" alt="スクリーンショット_2022-02-07_10_03_11" src="https://user-images.githubusercontent.com/54050089/152709915-ad4fefa0-9216-4879-9fa1-e4b9ef264709.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
